library(shinytest2)

test_that("{shinytest2} recording: Weight-Loss-Trends", {
  app <- AppDriver$new(name = "Weight-Loss-Trends", seed = 1, height = 711, width = 1139)
  app$set_inputs(drSimple = "2021-02-02")
  app$set_inputs(drSimple = "2022-02-02")
  app$set_inputs(drSimple = "2023-01-03")
  app$set_inputs(drSimple = "2022-11-04")
  app$set_inputs(smoothing = 0.75)
  app$set_inputs(smoothing = 0.1)
  app$set_inputs(smoothing = 0.45)
  app$set_inputs(showGoal = TRUE)
  app$set_inputs(showGoal = FALSE)
  app$set_inputs(showMM = TRUE)
  app$set_inputs(showGoal = TRUE)
  app$set_inputs(model30 = FALSE)
  app$set_inputs(model30 = TRUE)
  app$set_inputs(fitdays = 39)
  app$set_inputs(smoothing = 0.2)
  app$set_inputs(goalwt = 205)
  app$set_inputs(goalwt = 225)
  app$expect_values()
  app$set_inputs(drSimple = "2022-02-02")
  app$set_inputs(smoothing = 0.75)
  app$expect_values()
  app$set_inputs(goalwt = 190)
  app$expect_values()
})

