library(shinytest2)

test_that("Migrated shinytest test: mytest.R", {
  app <- AppDriver$new()

  app$set_inputs(drSimple = "2021-02-02")
  app$set_inputs(drSimple = "2022-02-02")
  app$set_inputs(drSimple = "2023-01-03")
  app$set_inputs(smoothing = 0.8)
  app$set_inputs(smoothing = 0.2)
  app$set_inputs(smoothing = 0.45)
  app$set_inputs(smoothing = 0.5)
  app$set_inputs(showGoal = TRUE)
  app$set_inputs(showMM = TRUE)
  app$set_inputs(model30 = FALSE)
  app$set_inputs(goalwt = 210)
  app$set_inputs(goalwt = 195)
  app$set_inputs(goalwt = 210)
  app$set_inputs(goalwt = 225)
  app$set_inputs(tabs = "Model Stats")
  app$set_inputs(tabs = "Table")
  app$set_inputs(tabs = "Info")
  app$set_inputs(drSimple = "2022-11-04")
  app$set_inputs(drSimple = "2021-02-02")
  app$set_inputs(drSimple = "2022-02-02")
  app$set_inputs(smoothing = 0.25)
  app$set_inputs(model30 = TRUE)
  app$set_inputs(fitdays = 17)
  app$set_inputs(tabs = "Stats")
  app$expect_values()
  app$expect_screenshot()
})
