name: docker

on:
  branches:
  - main
  push:
    paths:
    - '.github/workflows/alpine-r/**'
    - '.github/workflows/alpine-r.yml'
  schedule:
  - cron: "0 0 1 * *"
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .gihub/workflows/alpine-r/
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/alpine-r:latest
