name: Push Weight-Loss-Trends

on:
  push:
    branches:
      - dev

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: install2.R -n -1 rsconnect


