name: Push Weight-Loss-Trends

on:
  push:
    branches:
      - dev

jobs:
  Deploy:
    runs-on: ubuntu-latest
    env:
      CRAN: https://packagemanager.posit.co/cran/__linux__/jammy/latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo chmod 777 -R /usr/local/lib/R/site-library
      - run: Rscript -e "install.packages('docopt')"
      - run: ./install2.R -n -1 shiny tidyr dplyr lubridate ggplot2 readr rsconnect reactable shinydashboard shinyjs shinyWidgets
      - run: Rscript -e "library('rsconnect')"


