name: Push Weight-Loss-Trends

on:
  push:
    branches:
      - dev

jobs:
  Deploy:
    runs-on: ubuntu-latest
    env:
      DIR: IWF-Data-Explorer/
      CRAN: https://packagemanager.posit.co/cran/__linux__/jammy/latest
      TOKEN: ${{secrets.TOKEN}}
      SECRET: ${{secrets.SECRET}}
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install libcurl4-openssl-dev
      - run: sudo chmod 777 -R /usr/local/lib/R/site-library
      - run: ./deploy.R


