name: Push IWF-Data-Explorer

on:
  push:
    paths:
      - IWF-Data-Explorer/**

  workflow_dispatch:


jobs:
  Push-to-shinyapps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: execute
        run: >
          docker run
          -e DIR=IWF-Data-Explorer
          -e TOKEN=${{secrets.TOKEN}}
          -e SECRET=${{secrets.SECRET}}
          -v "$(pwd)"/:/home/shinyusr
          dankypants/shinypush


