name: Push IWF-Data-Explorer

on:
  push:
    paths:
      - IWF-Data-Explorer/**

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: execute
        run: >
          docker run
          -e DIR=IWF-Data-Explorer
          -e TOKEN=${{secrets.TOKEN}}
          -e SECRET=${{secrets.SECRET}}
          -v "$(pwd)"/:/workdir
          dankypants/shiny-push


