name: Push IWF-Data-Explorer

on:
  push:
    branches:
      - main
    paths:
      - IWF-Data-Explorer/**
      - .github/workflows/iwf-data-explorer.yml

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy With rsconnect
        run: >
          docker run
          -e DIR=IWF-Data-Explorer
          -e TOKEN=${{secrets.TOKEN}}
          -e SECRET=${{secrets.SECRET}}
          -v "$(pwd)"/:/workdir
          ${{ secrets.DOCKER_USERNAME }}/shiny-push:latest
          Rscript deploy.R


