name: Push IWF-Data-Explorer

on:
  push:
    branches:
      - main
    paths:
      - IWF-Data-Explorer/**
  pull_request:
    branches:
      - main
    paths:
      - IWF-Data-Explorer/**


jobs:
  Push-to-shinyapps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: execute
        run: >
          docker run
          -e DIR=IWF-Data-Explorer
          -e TOKEN=${{secrets.TOKEN}}
          -e SECRET=${{secrets.SECRET}}
          -v "$(pwd)"/:/workdir
          dankypants/shinypush


