name: Push R6-Stats

on:
  push:
    paths:
      - R6-Stats/**

  workflow_dispatch:


jobs:
  Push-to-shinyapps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: execute
        run: >
          docker run
          -e DIR=R6-Stats
          -e TOKEN=${{secrets.TOKEN}}
          -e SECRET=${{secrets.SECRET}}
          -v "$(pwd)"/:/workdir
          dankypants/shinypush


