name: Setup Docker

on:
  branches:
  - main
  push:
    paths:
    - '.github/workflows/shiny-push/**'
    - '.github/workflows/shiny-push.yml'
  schedule:
  - cron: "0 0 1,15 * *"
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .gihub/workflows/shiny-push/
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/shiny-push:latest
