name: Push Weight-Loss-Trends

env:
  RENV_PATHS_ROOT: ~/.local/share/renv

on:
  push:
    branches:
      - main
    paths:
      - Weight-Loss-Trends/**
      - .github/**

jobs:
  Push-to-shinyapps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install libcurl4-openssl-dev

      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Restore packages
        run: Rscript -e "renv::restore()""

      - run: |
          Rscript -e "
            library(rsconnect)
            setAccountInfo(
                name = 'cluffa',
                token = ${{secrets.TOKEN}},
                secret = ${{secrets.SECRET}}
            )

            deployApp(
                appName = 'Weight-Loss-Trends',
                forceUpdate = TRUE,
                launch.browser = FALSE
            )
          "



