name: Push Weight-Loss-Trends

on:
  push:
    branches:
      - main
    paths:
      - Weight-Loss-Trends/**
      - .github/workflows/**

jobs:
  Push-to-shinyapps:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2

      - run: Rscript -e "library(rsconnect); setAccountInfo( ${{ secrets.USER }}, ${{ secrets.TOKEN }}, ${{ secrets.SECRET }}); deployApp(appDir = 'Weight-Loss-Trends', forceUpdate = TRUE, launch.browser = FALSE)"



