name: Push Weight-Loss-Trends

on:
  push:
    paths:
      - Weight-Loss-Trends/**
      - .github/workflows/weight-loss-trends.yml
      - Dockerfile

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

    - name: Cache
      id: cache-r-pack
      uses: actions/cache@v3
      with:
        path: r-pack
        key: ${{ runner.os }}-r-pack

      - run: Rscript -e "print(.libPaths())"
      - run: mkdir r-pack/
      - run: Rscript -e "install.packages('rsconnect', lib = 'r-pack/')"
      #- run: Rscript -e ".libPaths('r-pack/'); library(rsconnect)"
      - run: Rscript -e "library(rsconnect, lib.loc = 'r-pack/')"

      # - name: Setup Buildx
      #   uses: docker/setup-buildx-action@v2
      
      # - name: Build
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     push: false
      #     load: true
      #     tags: shiny-push:latest
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max

      # - name: Test rsconnect
      #   if: github.ref != 'refs/heads/main'
      #   run: >
      #     docker run
      #     -e DIR=Weight-Loss-Trends
      #     -e TOKEN=${{secrets.TOKEN}}
      #     -e SECRET=${{secrets.SECRET}}
      #     -v "$(pwd)"/:/workdir
      #     shiny-push:latest
      #     Rscript -e "library(rsconnect); print(.libPaths())"

      # - name: Deploy With rsconnect
      #   if: github.ref == 'refs/heads/main'
      #   run: >
      #     docker run
      #     -e DIR=Weight-Loss-Trends
      #     -e TOKEN=${{secrets.TOKEN}}
      #     -e SECRET=${{secrets.SECRET}}
      #     -v "$(pwd)"/:/workdir
      #     shiny-push:latest
      #     Rscript deploy.R
