name: Push Weight-Loss-Trends

on:
  push:
    branches:
      - main
    paths:
      - Weight-Loss-Trends/**
      - .github/workflows/weight-loss-trends.yml

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # - name: Buildx
      #   uses: docker/setup-buildx-action@v1

      # - name: Login
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      
      # - name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .github/workflows/
      #     push: false
      #     tags: shinypush
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max

  # It also restores the cache if it exists.
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: Build the Docker image
        run: docker build .github/workflows/ -t sp:latest

    
      - name: Deploy With rsconnect
        run: >
          docker run
          -e DIR=Weight-Loss-Trends
          -e TOKEN=${{secrets.TOKEN}}
          -e SECRET=${{secrets.SECRET}}
          -v "$(pwd)"/:/workdir
          sp:latest
          Rscript deploy.R


