name: Push Weight-Loss-Trends

on:
  push:
    branches:
      - main
    paths:
      - Weight-Loss-Trends/**
      - .github/workflows**

jobs:
  Push-to-shinyapps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install --no-install-recommends software-properties-common dirmngr
      - run: sudo add-apt-repository -y ppa:c2d4u.team/c2d4u4.0+
      - run: >
        sudo apt install -y --no-install-recommends \
        r-base \
        r-cran-rsconnect \
        r-cran-dplyr \
        r-cran-tidyr \
        r-cran-ggplot2 \
        r-cran-lubridate \
        r-cran-readr \
        r-cran-reactable \
        r-cran-shiny \
        r-cran-shinydashboard \
        r-cran-shinyjs \
        r-cran-shinywidgets

      - run: |
          Rscript -e "
            library(rsconnect)
            setAccountInfo(
                name = ${{secrets.USER}},
                token = ${{secrets.TOKEN}},
                secret = ${{secrets.SECRET}}
            )

            deployApp(
                appDir = 'Weight-Loss-Trends',
                forceUpdate = TRUE,
                launch.browser = FALSE
            )
          "



