name: Push Weight-Loss-Trends

on:
  push:
    branches:
      - main
    paths:
      - Weight-Loss-Trends/**
  pull_request:
    branches:
      - main
    paths:
      - Weight-Loss-Trends/**

jobs:
  Push-to-shinyapps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: execute
        run: >
          docker run
          -e DIR=Weight-Loss-Trends
          -e TOKEN=${{secrets.TOKEN}}
          -e SECRET=${{secrets.SECRET}}
          -v "$(pwd)"/:/workdir
          dankypants/shinypush


