name: Push Weight-Loss-Trends

on:
  push:
    branches:
      - main
    paths:
      - Weight-Loss-Trends/**

jobs:
  Push-to-shinyapps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install R R-dev g++
      - run: R -e "install.packages(renv, repos = 'http://cran.us.r-project.org')"
      - run: R -e "renv::init()"
      - run: R -e "renv::dependencies()"
      - run: R -e "source('renv/activate.R'); library(rsconnect)"


