app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$setInputs(drSimple = "2021-02-02")
app$setInputs(drSimple = "2022-02-02")
app$setInputs(drSimple = "2023-01-03")
app$setInputs(smoothing = 0.8)
app$setInputs(smoothing = 0.2)
app$setInputs(smoothing = 0.45)
app$setInputs(smoothing = 0.5)
app$setInputs(showGoal = TRUE)
app$setInputs(showMM = TRUE)
app$setInputs(model30 = FALSE)
app$setInputs(goalwt = 210)
app$setInputs(goalwt = 195)
app$setInputs(goalwt = 210)
app$setInputs(goalwt = 225)
app$setInputs(tabs = "Model Stats")
app$setInputs(tabs = "Table")
app$setInputs(tabs = "Info")
app$setInputs(drSimple = "2022-11-04")
app$setInputs(drSimple = "2021-02-02")
app$setInputs(drSimple = "2022-02-02")
app$setInputs(smoothing = 0.25)
app$setInputs(model30 = TRUE)
app$setInputs(fitdays = 17)
app$setInputs(tabs = "Stats")
app$snapshot()
